config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  get 'androidblog/index'

  devise_for :users
  
  root 'androidblog#index'
 
  resources :articles do
    resources :comments
    member do
    get :update_published_at
  end 
end
resources :androidblog

  

end

app/models/article.rb
class Article < ActiveRecord::Base
	validates :title ,:body, presence: true,
                    length: { minimum: 5 }
    has_many :comments
    has_attached_file :attachment,
    	:styles => {
		  :thumb    => ['100x100#',  :jpg, :quality => 70],
		  :medium	=> ['480x480#',  :jpg, :quality => 70],
		  :preview  => ['480x480#',  :jpg, :quality => 70],
		  :large    => ['600>',      :jpg, :quality => 70],
		  :retina   => ['1200>',     :jpg, :quality => 30]
			}
	validates_attachment_content_type :attachment, :content_type => /\Aimage\/.*\Z/
	acts_as_taggable_on :tags
	belongs_to :user
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    :url => "/ckeditor_assets/attachments/:id/:filename",
                    :path => ":rails_root/public/ckeditor_assets/attachments/:id/:filename"

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    :url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :styles => { :content => '800>', :thumb => '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 2.megabytes
  validates_attachment_content_type :data, :content_type => /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  def index
  end
end

app/controllers/androidblog_controller.rb
class AndroidblogController < ApplicationController
def new
		 @article = Article.new
	end
  def index
  		 if params[:tag].present? 
      		@articles = Article.tagged_with(params[:tag]).paginate(page: params[:page], per_page: 10)
   		 else 
     		 @articles =Article.paginate(page: params[:page], per_page: 10)
    	 end  
	end
	def show
  		 @article = Article.find(params[:id])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    articles_path
  end

  def after_sign_up_path_for(resource)
    articles_path
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
before_action :authenticate_user!, :only => [:new,:create,:edit,:destroy,:index]
before_filter :require_permission, :only => [:edit,:destroy,:update_published_at]
	def new
		 @article = Article.new
	end
	def create
		@user=current_user.id
		 @article = Article.new(article_params)
		  @article.user_id=@user
 		if @article.save
 		 redirect_to @article
 		 else
	     render 'new'
	 	end
    end
    def show
  		 @article = Article.find(params[:id])
	end
	def index
  		 if params[:tag].present? 
      		@articles = Article.tagged_with(params[:tag]).paginate(page: params[:page], per_page: 3)
   		 else 
     		 @articles =Article.paginate(page: params[:page], per_page: 3)
    	 end
    	   
	end
	def edit
  		@article = Article.find(params[:id])
	end
	def update
		@article=Article.find(params[:id])
		if @article.update(article_params)
			redirect_to @article
		else
			render 'edit'
		end
	end
	def destroy
 		 @article = Article.find(params[:id])
 		 @article.destroy
		 redirect_to articles_path
	end
	def update_published_at
		@article = Article.find(params[:id])
		if @article.published_at == nil
			publish_time=Time.now
			 @article.update_attributes(:published_at=> publish_time.strftime("%B %d, %Y"))
			 redirect_to articles_path
		else
			publish_time=nil
			 @article.update_attributes(:published_at=> publish_time)
			 redirect_to articles_path
		end
		
	end

	def require_permission
     @article = Article.find(params[:id])
      if current_user.id != @article.user_id
      flash[:notice] = "You cannot edit/delete this article"
      redirect_to articles_path 
      end
  end

  private
  	def article_params
    	params.require(:article).permit(:title, :body, :tag_list,:attachment)
  	end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@article=Article.find(params[:article_id])
		@comment=@article.comments.create(comment_params)
		@total_comment=@article.total_comment+1
		if @article.update_attributes(:total_comment=> @total_comment)
		redirect_to androidblog_path(@article)
		else
		redirect_to article_path(@article)
		end
	end
 private
    def comment_params
      params.require(:comment).permit(:commenter, :body, :email)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/androidblog_helper.rb
module AndroidblogHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
	include ActsAsTaggableOn::TagsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/admin/index.html.erb
<h1>MYTG BLOG</h1>

app/views/androidblog/index.html.erb
<div class="container">
   <% @articles.each do |article| %>
   <% if article.published_at != nil %>
   <div class="blog_title"><%= link_to article.title, androidblog_path(article),:class=>'title_link' %></div>
   <div class="detail_row">
        <span class="date">
            <%= article.published_at %>
        </span>
        <span class="comment">
            <%= article.total_comment %> Comments
        </span>
   </div>
   <div class="attach">
    <%= image_tag article.attachment.url(:large) ,:class=>'attach_img' %>
   </div>
   <div class="content">
    <% strip_content=article.body.scan(/.{1,500}/m) %>
     <%= raw strip_content[0] << '......' %>
   </div>
   <div class="read_button">
    <%= link_to 'Read More', androidblog_path(article) ,:class=>'read_more' %>
   </div>
   <div class="seperator"></div>
  <% end %>
  <% end %>
</div>

app/views/androidblog/show.html.erb
<div class="container">
	<div class="blog_title">
  			<%= @article.title %>
	</div> 

  <div class="detail_row">
    <span class="date">
      <%= @article.published_at %>
    </span>
    <span class="comment">
      <%= @article.total_comment %> Comments
    </span>
  </div>
	<div class="attach">
    <%= image_tag @article.attachment.url(:large) ,:class=>'attach_img' %>
  </div>
  <div class="content">
     <%=raw @article.body %>
  </div>

  <div class="tags">
		<strong class="tag_head">Tags</strong>
  		<% @article.tags.any? %>
  		<% @article.tags.each do |tag| %>
  		<%= link_to tag.name, androidblog_index_url(:tag => tag.name) ,:class=>'tag_name' %>
		<% end %>
  </div>


<div class="comment_container">
  <span class="comment_head">Comments</span>
  <span class="comment_count">(  <%= @article.total_comment %>  Comments )</span>
  <div class="comment_content">
     <% @article.comments.each do |comment| %>
     <span class="commenter">
       <%= comment.commenter %>
     </span>
     <span class="commenter_date">
       <%= comment.created_at.strftime("%d %b. %Y") %>
     </span>
     <br>
     <p class="comment_body">
       <%= comment.body %>
     </p>
     <hr>
     <% end %>
</div>
<p class="add_comment">Leave a Comment</p>
<div class="new_comment">
    <%= form_for([@article, @article.comments.build]) do |f| %>
  <div class="row">
    <div class="large-2 columns">
      <%= f.label :Name %>
    </div>
    <div class="large-8 columns">
      <%= f.text_field :commenter ,:placeholder=>'Enter your name',:class=>'input' %>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="large-2 columns">
      <%= f.label :Email %>
    </div>
    <div class="large-8 columns">
      <%= f.text_field :email ,:placeholder=>'Enter your Email',:class=>'input' %>
    </div>
  </div>
  <br>
   <div class="row">
    <div class="large-2 columns">
      <%= f.label :Comment %>
    </div>
    <div class="large-8 columns">
      <%= f.text_area :body , :placeholder=>'What\'s on your mind',  :columns=>'25', :rows=>'10',:class=>'input' %>
    </div>
  </div>
  <div class="submit"><%= f.submit :class=>'submit_comment' %></div>
    <% end %>
</div>
</div>
</div>

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
  <% if @article.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@article.errors.count, "error") %> prohibited
      this article from being saved:</h2>
    <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
<div class="container">
  <div class="rows">
    <div class="large-8 rows">
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
    </div>
    <div class="large-8 rows">
     <p>
    <%= f.label :text %><br>
    <%= f.cktext_area :body, rows:18 , :toolbar=>'Full'%>
    </p>
  </div>
  <div class="large-8 rows">
  <p>
      <%= f.label :Attachment %><br>
      <%= f.file_field :attachment %>
  </p>
</div>
<div class="large-8 rows">
  <p>
    <%= f.label :tags %>
    <%= f.text_field :tag_list %>
  </p>
</div>
  <p>
    <%= f.submit :class=>'button small'%>   
<%= link_to 'Back', articles_path ,:class=>'button small'%>
  </p>

<% end %>
</div>

app/views/articles/edit.html.erb
<h3>Editing article</h3>
 
<%= render 'form' %>

app/views/articles/index.html.erb
<h3>Listing articles</h3>

<div class="new_article"><%= link_to 'New Article', new_article_path, :class=>'article' %>
<%= link_to 'My Blog', root_path, :class=>'blog' %></div> 
<br>
<div class="blog_content">
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="2"></th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= link_to article.title , article_path(article) %></td>
     <% strip_content=article.body.scan(/.{1,200}/m) %>
     <td><%=raw strip_content[0] << '......' %></td>
      <td><%= link_to 'Show', article_path(article) ,:class=>'button small' %></td>
      <td><%= link_to 'Edit', edit_article_path(article),:class=>'button small' %></td>
      <% if article.published_at == nil %>
      <td><%= link_to "Publish", update_published_at_article_path(article),:class=>'button small'  %></td>
      <% else %>
      <td><%= link_to "UnPublish", update_published_at_article_path(article),:class=>'button small'  %></td>
      <% end %>
       <td><%= link_to 'Destroy', article_path(article),:class=>'button small',
                    method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
</div>
<%= will_paginate @article %>

app/views/articles/new.html.erb
<h3>New Article</h3>

<%= render 'form' %>

app/views/articles/show.html.erb
<div class="container">
	<div class="blog_title">
  			<%= @article.title %>
	</div> 

  <div class="detail_row">
    <span class="date">
      <%= @article.published_at %>
    </span>
    <span class="comment">
      0 Comments
    </span>
  </div>
	<div class="attach">
    <%= image_tag @article.attachment.url(:large) ,:class=>'attach_img' %>
  </div>
  <div class="content">
     <%=raw @article.body %>
  </div>

  <div class="tags">
		<strong class="tag_head">Tags</strong>
  		<% @article.tags.any? %>
  		<% @article.tags.each do |tag| %>
  		<%= link_to tag.name, androidblog_index_url(:tag => tag.name) ,:class=>'tag_name' %>
		<% end %>
  </div>
  <br><br>
	<%= link_to 'Back', articles_path ,:class=>'button small' %> 	<%= link_to 'Edit', edit_article_path(@article) ,:class=>'button small'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "MYTG Blog" %></title>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= javascript_include_tag 'ckeditor/ckeditor.js' %>
    <%= csrf_meta_tags %>
  </head>

  <body>
<nav class="top-bar">
  <ul class="title-area">
    <li class="title">
      <%= link_to "MY TRAVEL GENIE", root_path %>
    </li>
  </ul>
  <section class="top-bar-section">
    <ul class="right">
      <% if user_signed_in? %>
        <li class="logged_in_msg">Signed in as <%= current_user.email %> Not you?</li>
        <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
      <% else %>
        <li><%= link_to "Sign Up",new_user_registration_path %></li> 
        <li><%= link_to "Sign In", new_user_session_path %></li>
      <%  end %>
    </ul>
  </section>
</nav>

    <%= yield %>
  </body>
</html>